### ISSUE TITLE
Email not found, Check your email address and try again!

### ISSUE THREAD

**Issue by pluveto** [yi-ge/chatgpt-api#2]
求助。bt：

```
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    email_chat_map[email] = Chat(email=email,
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/main.py", line 50, in __init__
    self._setup()
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/main.py", line 139, in _setup
    self._create_access_token()
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/main.py", line 157, in _create_access_token
    openai_auth.create_token()
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 131, in create_token
    self._part_two()
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 157, in _part_two
    self._part_three(token=csrf_token)
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 190, in _part_three
    self._part_four(url=url)
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 218, in _part_four
    self._part_five(state=state)
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 260, in _part_five
    self._part_six(state=state, captcha=captcha_input)
  File "/home/ubuntu/repo/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 301, in _part_six
    raise Exceptions.Auth0Exception("[OpenAI][6] Email not found, Check your email address and try again!")
PyChatGPT.src.pychatgpt.classes.exceptions.Auth0Exception: [OpenAI][6] Email not found, Check your email address and try again!
```

检查了变量，email 设置过。

**Comment by yi-ge** [comment]
拉取最新版本，修改account.json重试即可。

**Comment by pluveto** [comment]
最新版本直接卡在第一步。

```
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
```

能不能不要自动登录了，我手动复制 token

**Comment by pluveto** [comment]
我看是 openai 把 cloudflare 加上了，把各路 bot 赶尽杀绝

**Comment by yi-ge** [comment]
是的，这个我能轻松绕过，现在需要参考法务意见。主要是目前没时间弄。

**Comment by pluveto** [comment]
要是官方给个API就好了---- On Tue, 2022-12-13 17:48:12  ***@***.***> wrote ----  
是的，这个我能轻松绕过，现在需要征求法务意见。主要是目前没时间弄。

**Comment by yi-ge** [comment]
是的
