### ISSUE TITLE
PyChatGPT.src.pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again

### ISSUE THREAD

**Issue by ludashi2020** [yi-ge/chatgpt-api#4]
`[root@dbci chatgpt-api]# python3 main.py
[OpenAI] Email address: eco*****@gmail.com
[OpenAI] Password: er*******
[OpenAI] Beginning auth process
[OpenAI][1] Making request to https://chat.openai.com/auth/login
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    options=options)
  File "/home/wwwroot/chatgpt-api/PyChatGPT/src/pychatgpt/main.py", line 50, in __init__
    self._setup()
  File "/home/wwwroot/chatgpt-api/PyChatGPT/src/pychatgpt/main.py", line 139, in _setup
    self._create_access_token()
  File "/home/wwwroot/chatgpt-api/PyChatGPT/src/pychatgpt/main.py", line 157, in _create_access_token
    openai_auth.create_token()
  File "/home/wwwroot/chatgpt-api/PyChatGPT/src/pychatgpt/classes/openai.py", line 133, in create_token
    raise Exceptions.Auth0Exception("Failed to make the first request, Try that again!")
PyChatGPT.src.pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again!`

登录报错。

**Comment by yi-ge** [comment]
参考`chat.wyr.me`的alert，目前需要参考法务意见。
